### ISSUE TITLE
[A project suggestion] ML with data: Molecular Properties prediction

### ISSUE THREAD

**Issue by Osgood001** [wangleiphy/ml4p#1]
### This issue suggests an open competition that took place in Kaggle four years ago.

![image](https://user-images.githubusercontent.com/60919782/222942307-83a3789d-9c5d-4681-9254-72be5a144204.png)
[Problem Page](https://www.kaggle.com/competitions/champs-scalar-coupling/overview)

### [TL;DR]
**Scientific ML with data**: Use the data to develop an algorithm to predict the interaction between two atoms in a molecule.

Background in DFT, MD would be helpful.

## Pros

- It requires not only brute force ML practice, but also **domain knowledge in Computational Physics/Chemistry.**
- It is a **quantum many-body problem** that all Physics students would be familiar with.
- Well-documented and explained notebooks are publicly available, with **active updates recently** after four years.
- Kaggle provides a well-established **ranking and evaluation system**.

## Cons

- With so many open-source notebooks, it is hard to avoid plagiarism.
- Most codes are written with TensorFlow Keras instead of Jax.
- The computational demand for a good score is high.

Find your place in the score board! :smiley:

**Comment by wangleiphy** [comment]
looks good! 

Can one still join the competition ? 
If so, it is great to "Find your place in the score board!", no matter the result is.

**Comment by Osgood001** [comment]
Users who upload the solution file will receive scores. They can also join the competition and upload notebooks for verification.

This competition closed four years ago. New results may not show up directly on the leaderboard, and there is no award. :-))

![image](https://user-images.githubusercontent.com/60919782/222959929-042c31a9-e98f-44f5-86bb-5d4af3f5bedb.png)

**Comment by wangleiphy** [comment]
That is OK. 

Could you please prepare a PR for this at [this page](https://github.com/wangleiphy/ml4p/tree/main/projects) ? 

Thanks!
